# windows.yml
name: Windows
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          dir: C:\
          version: 5.14.2
          arch: win64_msvc2017_64
      - uses: actions/checkout@v3
      - name: build-RcloneBrowser-window64
        shell: cmd
        env:
          vc_arch: win64_msvc2017_64
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=c:\Qt\5.14.2\msvc2017_64 .. 
          echo "cmake done"
          cmake --build . --config Release
          echo "build msvc done"
          c:\Qt\5.14.2\msvc2017_64\bin\windeployqt.exe --no-translations --no-angle --no-compiler-runtime --no-svg ".\build\Release\RcloneBrowser.exe"
      - name: Gzip
        run: |
          Compress-Archive -Path build/build/Release RcloneBrowser.win64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: build/build/Release/RcloneBrowser.win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
